### ISSUE TITLE
illegal base64 data at input byte

### ISSUE THREAD

**Issue by pepordev** [zc2638/drone-k8s-plugin#1]
Hi! 

I'm testing the plugin and i'm facing an issue when deploying. My configuration looks like this:

```yaml
  - name: deploy
    image: zc2638/drone-k8s-plugin
    settings:
      kubernetes_server: https://api:6443
      kubernetes_token:
        from_secret: k8s_token 
      kubernetes_ca_crt:
        from_secret: k8s_ca_crt #base64 encoded
      kubernetes_skip_tls: false
      namespace: management
      debug: true
      templates:
        - kubernetes/deployment.yaml
        - kubernetes/service.yaml
        - kubernetes/ingress.yaml
      app_name: ${DRONE_REPO_NAME}
      host: myapp.example.com
      version: ${DRONE_TAG}
```

and templates like this
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .env.app_name }}
  labels:
    app.kubernetes.io/name: {{ .env.app_name }}
    app.kubernetes.io/version: {{ .env.version }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .env.app_name }}
      app.kubernetes.io/version: {{ .env.version }}
  template:
    metadata:
      name: {{ .env.app_name }}
      labels:
        app.kubernetes.io/name: {{ .env.app_name }}
        app.kubernetes.io/version: {{ .env.version }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: {{ .env.app_name }}
          image: my-image:{{ .env.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
```
Am I missing something here?
