### ISSUE TITLE
How do I trigger redeployment?

### ISSUE THREAD

**Issue by vzcrab** [zc2638/drone-k8s-plugin#2]
I want to pull a new image through redeployment. If you have a better solution, please let me know.

**Comment by zc2638** [comment]
You can put your image version into a variable image, you can use `drone_build_number`. 
After each build is a new mirror version.

**Comment by vzcrab** [comment]
```
  - name: docker image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      ……
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
  - name: k8s deploy
    image: zc2638/drone-k8s-plugin
    settings:
      ……
      templates:
        - deployment.yaml
        - service.yaml
      app_name: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}
```

Thank you for reply.

I browse some information. It seems to use like `{{ .env.version }}`, but I can't find what this is.

**Comment by zc2638** [comment]
You can define the parameters you need in `settings`, which will be converted into `env` variables.
e.g. 
```yaml
---
kind: pipeline
type: docker
name: drone-k8s-plugin-test

steps:
  - name: deploy
    image: zc2638/drone-k8s-plugin
    pull: if-not-exists
    settings:
      ...
      app_name: ${DRONE_REPO_NAME}
      image_version: ${DRONE_BUILD_NUMBER}
```
`image_version` is defined above, you can use `{{ .env.image_version }}` as a variable.
In addition, you can also set the environment variables you need separately in the pipeline, which can also achieve the purpose.
